wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.999
data_augmentation:
  value: false
data_scaling:
  value: min_max
epochs:
  value: 10
epsilon:
  value: 1.0e-06
hidden_size:
  value: 128
loss_func:
  value: mean_squared_error
lr:
  value: 0.0001
momentum:
  value: 0.9
n_hidden:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_initialization:
  value: Xavier
